#' Simulate left-truncated and right-censored data
#'
#' Simulates data under left truncation and right censoring.
#'
#' @param n Sample size.
#' @param rtrunc A function generating truncation times.
#' @param trunc.args A list of arguments passed to `rtrunc`.
#' @param rtarget A function generating target/event times.
#' @param target.args A list of arguments passed to `rtarget`.
#' @param rcens A function generating residual censoring times.
#' @param cens.args A list of arguments passed to `rcens`.
#' @param seed Optional seed.
#'
#' @examples
#' aa <- ltrc.sim(n=500,rtrunc=rnorm,trunc.args=list(4,1),
#' rtarget=rnorm,target.args = list(4,1),
#' rcens=rexp,cens.args=list(1),seed=12)
#' head(aa)
#'
#' @return A data frame with columns `u`, `y`, and `delta`.
#' @export
ltrc.sim <- function(n,
                     rtrunc, trunc.args = list(),
                     rtarget, target.args = list(),
                     rcens, cens.args = list(),
                     seed = NULL) {


  if (!is.numeric(n) || length(n) != 1L || !is.finite(n) ||
      n <= 0 || n != as.integer(n)) {
    stop("'n' must be one positive integer.")
  }
  n <- as.integer(n)

  if (!is.function(rtrunc)) {
    stop("'rtrunc' must be a function generating truncation times.")
  }

  if (!is.function(rtarget)) {
    stop("'rtarget' must be a function generating target/event times.")
  }

  if (!is.function(rcens)) {
    stop("'rcens' must be a function generating residual censoring times.")
  }

  if (!is.list(trunc.args)) {
    stop("'trunc.args' must be a list.")
  }

  if (!is.list(target.args)) {
    stop("'target.args' must be a list.")
  }

  if (!is.list(cens.args)) {
    stop("'cens.args' must be a list.")
  }

  if (!is.null(seed)) {
    set.seed(seed)
  }


  draw_from <- function(rfun, size, args, name) {
    out <- tryCatch(
      do.call(rfun, c(list(n = size), args)),
      error = function(e) {
        stop(sprintf("Error while calling '%s': %s", name, e$message), call. = FALSE)
      }
    )

    if (!is.numeric(out)) {
      stop(sprintf("'%s' must return a numeric vector.", name))
    }

    if (length(out) != size) {
      stop(sprintf("'%s' must return a numeric vector of length 'n'.", name))
    }

    if (any(!is.finite(out))) {
      stop(sprintf("'%s' returned non-finite values.", name))
    }

    out
  }

  batch.size <- max(1000L, n)
  max.draws  <- 1e7


  u.keep <- numeric(n)
  x.keep <- numeric(n)

  n.accepted  <- 0L
  n.generated <- 0L

  while (n.accepted < n) {

    m <- min(batch.size, max.draws - n.generated)

    if (m <= 0L) {
      stop(
        paste(
          "Maximum number of generated pairs reached before obtaining 'n' observable pairs.",
          "Try using distributions with a larger probability of satisfying U <= X."
        ),
        call. = FALSE
      )
    }

    u.new <- draw_from(rtrunc, size = m, args = trunc.args, name = "rtrunc")
    x.new <- draw_from(rtarget, size = m, args = target.args, name = "rtarget")

    ok <- (u.new <= x.new)
    n.ok <- sum(ok)

    if (n.ok > 0L) {
      take <- min(n - n.accepted, n.ok)
      idx <- which(ok)[seq_len(take)]

      rng <- (n.accepted + 1L):(n.accepted + take)
      u.keep[rng] <- u.new[idx]
      x.keep[rng] <- x.new[idx]

      n.accepted <- n.accepted + take
    }

    n.generated <- n.generated + m
  }



  resid.cens <- draw_from(rcens, size = n, args = cens.args, name = "rcens")

  if (any(resid.cens <= 0)) {
    stop(
      paste(
        "The residual censoring times generated by 'rcens' must be strictly positive.",
        "Please use a distribution with positive support (e.g. exponential, Weibull, gamma, lognormal)."
      ),
      call. = FALSE
    )
  }

  ctime <- u.keep + resid.cens
  y <- pmin(x.keep, ctime)
  delta <- as.numeric(x.keep <= ctime)


  out <- data.frame(
    u = u.keep,
    y = y,
    delta = delta
  )

  attr(out, "n.generated") <- n.generated
  attr(out, "acceptance.rate") <- n / n.generated
  attr(out, "censoring.rate") <- mean(delta == 0)
  attr(out, "call") <- match.call()

  class(out) <- c("ltrc_sample", class(out))

  return(out)
}
