#' Right-censored data simulation
#'
#' Simulates right-censored survival data from prespecified event-time and
#' censoring-time distributions.
#'
#' @param n Sample size.
#' @param rtarget A function that simulates event/survival times.
#' @param target.args A list with the parameters of the target distribution.
#' @param rcens A function that simulates censoring times.
#' @param cens.args A list with the parameters of the censoring distribution.
#' @param seed Optional seed for reproducibility.
#'
#' @return
#' A data frame with \eqn{n} rows and two columns:
#' \describe{
#'   \item{y}{Observed follow-up time, i.e. \eqn{\min(X, C)}.}
#'   \item{delta}{Event indicator, equal to 1 if the event is observed and 0 if censored.}
#' }

#'
#' @examples
#' aa <- rc.sim(n = 1000, rtarget = rweibull,
#' target.args = list(shape = 2, scale = 3),
#' rcens = rexp, cens.args = list(rate = 0.2),
#' seed = 123)
#' head(aa)
#' mean(aa$delta == 0)  # empirical censoring rate
#'
#' @export
#'
rc.sim <- function(n,
                   rtarget, target.args = list(),
                   rcens, cens.args = list(),
                   seed = NULL) {


  if (!is.numeric(n) || length(n) != 1L || !is.finite(n) ||
      n <= 0 || n != as.integer(n)) {
    stop("'n' must be one positive integer.", call. = FALSE)
  }
  n <- as.integer(n)

  if (!is.function(rtarget)) {
    stop("'rtarget' must be a function generating event times.", call. = FALSE)
  }

  if (!is.function(rcens)) {
    stop("'rcens' must be a function generating censoring times.", call. = FALSE)
  }

  if (!is.list(target.args)) {
    stop("'target.args' must be a list.", call. = FALSE)
  }

  if (!is.list(cens.args)) {
    stop("'cens.args' must be a list.", call. = FALSE)
  }

  if (!is.null(seed)) {
    set.seed(seed)
  }


  draw_from <- function(rfun, size, args, name) {
    out <- tryCatch(
      do.call(rfun, c(list(n = size), args)),
      error = function(e) {
        stop(sprintf("Error while calling '%s': %s", name, e$message), call. = FALSE)
      }
    )

    if (!is.numeric(out)) {
      stop(sprintf("'%s' must return a numeric vector.", name), call. = FALSE)
    }

    if (length(out) != size) {
      stop(sprintf("'%s' must return a numeric vector of length 'n'.", name), call. = FALSE)
    }

    if (any(!is.finite(out))) {
      stop(sprintf("'%s' returned non-finite values.", name), call. = FALSE)
    }

    out
  }


  x <- draw_from(rtarget, size = n, args = target.args, name = "rtarget")
  ctime <- draw_from(rcens, size = n, args = cens.args, name = "rcens")

  if (any(x < 0)) {
    stop(
      paste(
        "The event times generated by 'rtarget' must be non-negative.",
        "Please use a distribution supported on [0, Inf)."
      ),
      call. = FALSE
    )
  }

  if (any(ctime < 0)) {
    stop(
      paste(
        "The censoring times generated by 'rcens' must be non-negative.",
        "Please use a distribution supported on [0, Inf)."
      ),
      call. = FALSE
    )
  }

  y <- pmin(x, ctime)
  delta <- as.integer(x <= ctime)

  out <- data.frame(
    y = y,
    delta = delta
  )

  attr(out, "censoring.rate") <- mean(delta == 0)
  attr(out, "call") <- match.call()

  class(out) <- c("rc_sample", class(out))

  out
}

